source <(kubectl completion bash)
alias k='kubectl'
complete -F __start_kubectl k
alias a='aws'
function k_ctx() {
    kubectl config use-context $1
}
function eks_login() {
    aws eks --region $2 update-kubeconfig --name $1
}
