version: '3.8'
services:
  cn-toolbox:
    container_name: cn-toolbox
    image: cn-toolbox
    entrypoint: ["sleep", "infinity"]
    build:
      context: .
    environment:
      AWS_VAULT: "${AWS_VAULT}"
      AWS_DEFAULT_REGION: "${AWS_DEFAULT_REGION}"
      AWS_REGION: "${AWS_REGION}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY}"
      AWS_SESSION_TOKEN: "${AWS_SESSION_TOKEN}"
      AWS_SECURITY_TOKEN: "${AWS_SECURITY_TOKEN}"
      AWS_SESSION_EXPIRATION: "${AWS_SECRET_ACCESS_KEY}"
    volumes:
      - type: bind
        source: "${PWD}/../"
        target: /infra/
      - type: bind
        source: "${HOME}/.kube"
        target: /home/dev/.kube
      - type: bind
        source: "${HOME}/.ssh"
        target: /home/dev/.ssh
